name: Deploy Next.js App

on:
  push:
    branches:
      - main # Укажите ветку, при пуше в которую должен идти деплой (main или master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Selectel Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Добавляем стандартные пути, где обычно лежат npm и pm2
            export PATH=$PATH:/usr/local/bin:/usr/bin:/bin

            # 2. Если вы устанавливали Node.js через nvm (Node Version Manager), загружаем его
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # --- Дальше ваш обычный скрипт ---

            cd /root/enlgihs-school-landing/

            git pull origin main

            npm install

            npm run build

            pm2 restart english-dome
